/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 29-июл-2021 15:18:43 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS event CASCADE
;

DROP TABLE IF EXISTS image CASCADE
;

DROP TABLE IF EXISTS period_type CASCADE
;

DROP TABLE IF EXISTS person CASCADE
;

DROP TABLE IF EXISTS task CASCADE
;

DROP TABLE IF EXISTS wish CASCADE
;

/* Create Tables */

CREATE TABLE event
(
    id serial NOT NULL,	-- Идентификатор
    name varchar(50) NOT NULL,	-- Название события
    start_date timestamp without time zone NOT NULL,	-- Дата начала
    period_type_id integer NOT NULL,	-- Тип периода события
    period_frequency integer NOT NULL,	-- Частота периода события
    recurring_count integer NOT NULL,	-- Количество повторений событий
    task_id integer NOT NULL	-- Идентификатор задачи
);

CREATE TABLE image
(
    id serial NOT NULL,
    data bytea NOT NULL,	-- Данные с изображением
    wish_id integer NOT NULL	-- Идентификатор желания
);

CREATE TABLE period_type
(
    id serial NOT NULL,	-- Идентификатор типа периода
    name varchar(50) NOT NULL	-- Название типа периода
);

CREATE TABLE person
(
    id serial NOT NULL,	-- Идентификатор пользователя
    name varchar(50) NOT NULL,	-- Имя пользователя
    email varchar(50) NOT NULL,	-- Электронная почта пользователя
    pass_salt varchar(50),	-- Модификатор входа хэш-функции
    pass varchar(50),	-- Пароль пользователя
    created_date timestamp without time zone NOT NULL	-- Дата создания аккаунта
);

CREATE TABLE task
(
    id serial NOT NULL,
    name varchar(50) NOT NULL,	-- Название задачи
    wish_id integer NOT NULL	-- Идентификатор желания
);

CREATE TABLE wish
(
    id serial NOT NULL,
    name varchar(50) NOT NULL,	-- Название желания
    due_date varchar(50) NULL,	-- Срок желания
    is_goal boolean NOT NULL,	-- Флаг является ли желание целью
    person_id integer NOT NULL	-- Идентификатор пользователя
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE event ADD CONSTRAINT "PK_event"
    PRIMARY KEY (id)
;

CREATE INDEX "IXFK_event_period_type" ON event (period_type_id ASC)
;

CREATE INDEX "IXFK_event_task" ON event (task_id ASC)
;

ALTER TABLE image ADD CONSTRAINT "PK_Table1"
    PRIMARY KEY (id)
;

CREATE INDEX "IXFK_image_wish" ON image (wish_id ASC)
;

ALTER TABLE period_type ADD CONSTRAINT "PK_period_type"
    PRIMARY KEY (id)
;

ALTER TABLE person ADD CONSTRAINT "PK_person"
    PRIMARY KEY (id)
;

ALTER TABLE task ADD CONSTRAINT "PK_task"
    PRIMARY KEY (id)
;

CREATE INDEX "IXFK_task_wish" ON task (wish_id ASC)
;

ALTER TABLE wish ADD CONSTRAINT "PK_wish"
    PRIMARY KEY (id)
;

CREATE INDEX "IXFK_wish_person" ON wish (person_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE event ADD CONSTRAINT "FK_event_task"
    FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE image ADD CONSTRAINT "FK_image_wish"
    FOREIGN KEY (wish_id) REFERENCES wish (id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE task ADD CONSTRAINT "FK_task_wish"
    FOREIGN KEY (wish_id) REFERENCES wish (id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE wish ADD CONSTRAINT "FK_wish_person"
    FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE Cascade ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE event
    IS 'Таблица событий'
;

COMMENT ON COLUMN event.id
    IS 'Идентификатор'
;

COMMENT ON COLUMN event.name
    IS 'Название события'
;

COMMENT ON COLUMN event.start_date
    IS 'Дата начала'
;

COMMENT ON COLUMN event.period_type_id
    IS 'Тип периода события'
;

COMMENT ON COLUMN event.period_frequency
    IS 'Частота периода события'
;

COMMENT ON COLUMN event.recurring_count
    IS 'Количество повторений событий'
;

COMMENT ON COLUMN event.task_id
    IS 'Идентификатор задачи'
;



COMMENT ON TABLE image
    IS 'Картинка цели'
;

COMMENT ON COLUMN image.data
    IS 'Данные с изображением'
;

COMMENT ON COLUMN image.wish_id
    IS 'Идентификатор желания'
;



COMMENT ON TABLE period_type
    IS 'Тип периода события'
;

COMMENT ON COLUMN period_type.id
    IS 'Идентификатор типа периода'
;

COMMENT ON COLUMN period_type.name
    IS 'Название типа периода'
;



COMMENT ON TABLE person
    IS 'Таблица пользователей'
;

COMMENT ON COLUMN person.id
    IS 'Идентификатор пользователя'
;

COMMENT ON COLUMN person.name
    IS 'Имя пользователя'
;

COMMENT ON COLUMN person.email
    IS 'Электронная почта пользователя'
;

COMMENT ON COLUMN person.pass_salt
    IS 'Модификатор входа хэш-функции'
;

COMMENT ON COLUMN person.pass
    IS 'Пароль пользователя'
;

COMMENT ON COLUMN person.created_date
    IS 'Дата создания аккаунта'
;



COMMENT ON TABLE task
    IS 'Таблица задач'
;

COMMENT ON COLUMN task.name
    IS 'Название задачи'
;

COMMENT ON COLUMN task.wish_id
    IS 'Идентификатор желания'
;



COMMENT ON TABLE wish
    IS 'Таблица с желаниями'
;

COMMENT ON COLUMN wish.name
    IS 'Название желания'
;

COMMENT ON COLUMN wish.due_date
    IS 'Срок желания'
;

COMMENT ON COLUMN wish.is_goal
    IS 'Флаг является ли желание целью'
;

COMMENT ON COLUMN wish.person_id
    IS 'Идентификатор пользователя'
;

 
